#!/bin/sh

memory=1G

init() {
	get_nya
	build_nya

	if [[ ! -f nya ]]; then
		echo "couldn't build nya"
		exit 1
	fi

	clone_repo
}

get_nya() {
	[[ -f nya ]] && rm nya
	[[ -d nya_src ]] && rm -rf nya_src

	git clone https://github.com/fafnirlinux/nya nya_src

	if [[ ! -d nya_src ]]; then
		echo "couldn't clone nya"
	fi
}

build_nya() {
	if [[ ! -d nya_src ]]; then
		echo "nya source doesn't exist"
		exit 1
	fi

	cd nya_src
	mkdir -p build
	cd build
	cmake ..
	make -j$(nproc)
	cp nya ../../
	cd ../../
}

clone_repo() {
	mkdir -p src
	cd src

	[[ -d pkg ]] && rm -rf pkg

	git clone https://github.com/fafnirlinux/repo pkg

	if [[ ! -d pkg ]]; then
		echo "couldn't clone repo"
		exit 1
	fi

	[[ -d stuff ]] && rm -rf stuff
	mv pkg/stuff .
	cd ..
}

build_stage0() {
	emerge kernel-headers
	emerge gcc3
	emerge make
	emerge patch
	emerge musl
	emerge libedit
	emerge netbsd-curses
	emerge bash
	emerge libz
	emerge libressl
	emerge libarchive
	emerge curl
	emerge nya
}

emerge() {
	./nya emerge $@
}

create_fs() {
	check_root

	./nya build filesystem
}

run() {
	if [[ ! -f fafnirlinux.iso ]]; then
		exit 1
	fi

	qemu-system-x86_64 -boot d -cdrom fafnirlinux.iso -m $memory
}

boot() {
	qemu-system-x86_64 -s -kernel iso/kernel -boot c -m $memory -hda iso/rootfs.gz -append "ro root=/dev/sr0"
}

iso() {
	if [[ ! -d rootfs ]]; then
		exit 1
	fi

	check_root

	mkdir -p iso
	cd rootfs

	[[ -f ../iso/rootfs.gz ]] && rm ../iso/rootfs.gz

	find . | cpio -R root:root -H newc -o | gzip > ../iso/rootfs.gz

	cd ..

	cp syslinux/isolinux.bin iso
	cp syslinux/isohdpfx.bin iso
	cp syslinux/ldlinux.c32 iso

	[[ ! -f iso/isolinux.cfg ]] && echo "default kernel initrd=rootfs.zst" > iso/isolinux.cfg

	cd iso

	xorriso \
		-as mkisofs \
		-o ../fafnirlinux.iso \
		-b isolinux.bin \
		-isohybrid-mbr isohdpfx.bin \
		-c boot.cat \
		-no-emul-boot \
		-boot-load-size 4 \
		-boot-info-table \
		./

	cd ..
}

check_root() {
	if [ "$EUID" -ne 0 ]; then
		echo "run as root"
		exit 1
	fi
}

enter_chroot() {
	sudo chroot rootfs /bin/ash
}

help() {
	echo idiot
}

main() {
	export STAGE=0

	case "$1" in
		init) init ;;
		stage0) build_stage0 ;;
		get-nya) get_nya ;;
		build-nya) build_nya ;;
		repo) clone_repo ;;
		chroot) enter_chroot ;;
		iso) iso ;;
		run) run ;;
		boot) boot ;;
		root) create_fs ;;
		build) shift; ./nya build $@ ;;
		install) shift; ./nya install $@ ;;
		remove) shift; ./nya remove $@ ;;
		*) emerge $@ ;;
	esac

	shift $((OPTIND -1))
}

main $@
