#!/bin/sh

if [ -z "`getent group synapse`" ]; then
  /usr/sbin/groupadd --system synapse
fi

if [ -z "`getent passwd synapse`" ]; then
  /usr/sbin/useradd -r -g synapse -d /var/lib/synapse -s /bin/false -c "synapse server" synapse
  /usr/bin/passwd -l synapse
fi
