#!/usr/bin/env sh
PKG_CONFIG_LIBDIR="/usr/lib/pkgconfig" \
PKG_CONFIG_PATH="/usr/lib/pkgconfig" \
PKG_CONFIG_SYSROOT_DIR="" \
PKG_CONFIG_SYSTEM_INCLUDE_PATH="/usr/include" \
PKG_CONFIG_SYSTEM_LIBRARY_PATH="/usr/lib" \
exec pkgconf "$@"
