.\"@ usocks - detour network traffic through SOCKS5 proxy.
.\"
.\" Public Domain
.
.Dd September 17, 2020
.Dt USOCKS 1
.Os
.
.
.Sh NAME
.Nm usocks
.Nd detour network traffic through SOCKS5 proxy
.
.
.Sh SYNOPSIS
.Nm
.Ar proxy-address
.Ar proxy-port
.Ar command
.Op Pf : Ar argument Ns \&:
.
.
.Sh DESCRIPTION
.
.Nm
can be used to detour stream-based network traffic of
.Ar command
through the specified SOCKS5 proxy.
This is realized by preloading a shared library which overwrites the
.Xr connect 2
system call.
Because of this simple approach the SOCKS5 provided DNS (name) lookup
mechanism is not used.
.Ar proxy-address
must be an IPv4 internet address (like
.Ql 127.0.0.1 ) .
For example
.
.Bd -literal -offset indent
# Login as USER on HOST, create a local SOCKS proxy on port 10000
$ ssh -D 10000 USER@HOST

# Thereafter use usocks(1) to proxy any command over it
$ usocks 127.0.0.1 10000 irssi
.Ed
.
.\" s-ts-mode
