#!//bin/sh
#
# /etc/rc.d/distccd: start/stop distcc daemon
#

USER="distcc"
GROUP="distcc"
RUNDIR="/var/run/distcc"
PIDFILE="$RUNDIR/distcc.pid"
PROG="/usr/sbin/distccd"
ARGS="--daemon --pid-file $PIDFILE"

# Allow overriding variables in separate file (except for PATH)
. /etc/distccd.conf
PATH="/sbin:/usr/sbin:/bin:/usr/bin"

case $1 in
start)
	[ -d "$RUNDIR" ] || install -o $USER -g $GROUP -d "$RUNDIR"
	start-stop-daemon --start --pidfile $PIDFILE --exec $PROG -- $ARGS
	;;
stop)
	start-stop-daemon --stop --retry 60 --user $USER --pidfile $PIDFILE --remove-pidfile
	;;
restart)
	$0 stop
	$0 start
	;;
status)
	start-stop-daemon --status --user $USER --pidfile $PIDFILE
	case $? in
	0) echo "$PROG running with pid: $(cat $PIDFILE)" ;;
	1) echo "$PROG not running, stale pidfile: $PIDFILE" ;;
	3) echo "$PROG not running" ;;
	4) echo "Unable to determine program status" ;;
	esac
	;;
*)
	echo "usage: $0 [start|stop|status|restart]"
	;;
esac

# End of file
